
import { TranslationData, Language } from './types';

// Helper function to merge partial translations with defaults (Deep Merge simplified)
const mergeTranslations = (base: TranslationData, update: any): TranslationData => {
  return {
    ...base,
    ...update,
    tiles: { ...base.tiles, ...update.tiles },
    ui: { ...base.ui, ...update.ui },
    selfService: { 
      ...base.selfService, 
      ...update.selfService,
      steps: { ...base.selfService.steps, ...update.selfService?.steps },
      franking: { 
         ...base.selfService.franking, 
         ...update.selfService?.franking,
         fields: { ...base.selfService.franking.fields, ...update.selfService?.franking?.fields }
      },
      letter: { ...base.selfService.letter, ...update.selfService?.letter },
      payment: { ...base.selfService.payment, ...update.selfService?.payment },
      chat: { ...base.selfService.chat, ...update.selfService?.chat }
    }
  };
};

const DE_DEFAULTS: TranslationData = {
    topTitle: "PostAssistant",
    pageTitle: "Willkommen bei der Post",
    chatHeaderTitle: "PostAssistant Chat",
    chatPlaceholder: "Schreibe deine Frage…",
    chatSendLabel: "Senden",
    orakelViewTitle: "Wie können wir helfen?",
    orakelViewSubtitle: "Wähle ein Thema oder beschreibe dein Anliegen.",
    tiles: {
      orakel: {
        title: "Assistent",
        desc: "Stelle deine Frage an unseren KI-Assistenten für schnelle Antworten und Lösungen.",
        btnText: "Assistent starten",
      },
      self: {
        title: "Self-Service Assistent",
        desc: "Erledigen Sie ihre Postgeschäfte direkt hier im Self-Service, bei Bedarf mit Unterstützung eines digitalen Assistenten.",
        btnText: "Paket aufgeben",
        btnPacket: "Paket aufgeben",
        btnLetter: "Brief versenden",
        btnPayment: "Einzahlung (mit Karte)",
        btnOther: "Alles andere"
      },
      video: {
        title: "Video-Beratung",
        desc: "Persönliche Beratung per Video-Call mit unseren Expertinnen und Experten.",
        btnText: "Beratung starten",
      },
    },
    ui: {
      back: "Zurück",
      next: "Weiter",
      confirm: "Bestätigen",
      cancel: "Abbrechen",
      finish: "Abschliessen",
      thinking: "Ich denke nach…",
      welcomeChat: "Grüezi! Ich bin dein PostAssistant. Wie kann ich dir heute helfen?",
      errorGeneric: "Es ist ein Fehler aufgetreten. Bitte versuchen Sie es später erneut.",
      errorMicrophone: "Mikrofonzugriff fehlgeschlagen. Bitte überprüfen Sie die Berechtigungen.",
      retry: "Erneut versuchen",
      pay: "Bezahlen"
    },
    selfService: {
      title: "Paket frankieren",
      titleLetter: "Brief versenden",
      titlePayment: "Einzahlung",
      titleChat: "Post Info",
      steps: {
        start: "Start",
        weigh: "Wiegen",
        address: "Adresse",
        format: "Format",
        options: "Versandart",
        pay: "Bezahlung",
        done: "Abschluss",
        scan: "Scan",
        details: "Details",
        check: "Prüfung"
      },
      franking: {
        destCH: "Schweiz / Liechtenstein",
        destInt: "Ausland",
        destIntNote: "Versenden ins Ausland ist hier nicht möglich. Bitte wenden Sie sich an den Schalter.",
        weighIntro: "Legen Sie Ihr Paket auf die Waage um zu starten.",
        weighAction: "Paket wiegen",
        weighing: "Paket wird analysiert...",
        detectedLabel: "Gewicht und Masse Ihres Pakets erkannt",
        weight: "Gewicht",
        length: "Länge",
        width: "Breite",
        height: "Höhe",
        addressSender: "Absender",
        addressReceiver: "Empfänger erfassen",
        isCompany: "Firma",
        isPrivate: "Privatperson",
        fields: {
          name: "Name, Vorname",
          street: "Strasse, Nr.",
          zip: "PLZ",
          city: "Ort"
        },
        shippingMethod: "Versandart auswählen",
        economy: "PostPac Economy",
        priority: "PostPac Priority",
        duration2days: "2 Werktage",
        duration1day: "Nächster Werktag",
        extras: "Zusatzleistung hinzufügen",
        signature: "Signatur",
        total: "Total",
        payTerminal: "Bitte nutzen Sie zur Zahlung das Kartenterminal.",
        payInstruction: "Zahlung mit Bargeld und TWINT nicht möglich",
        payButton: "Zahlung bestätigen",
        successTitle: "Vorgang erfolgreich",
        instruction1: "Quittung entnehmen.",
        instruction2: "Zahlungsbeleg aufbewahren.",
        instruction3: "Vorgang abgeschlossen.",
        feedbackTitle: "Wie zufrieden sind Sie mit Ihrer Erfahrung?",
        feedbackThanks: "Danke für Ihren Besuch!"
      },
      letter: {
        addressCheckTitle: "Brief Versenden - Adresse",
        addressCheckQuestion: "Haben Sie die Adresse auf dem Brief bereits erfasst?",
        addressCheckYes: "Ja\nAdresse ist vorhanden",
        addressCheckNo: "Nein\nAdresse erfassen",
        formatTitle: "Brief Versenden - Format",
        formatQuestion: "Welches Format hat ihre Sendung?",
        formatSmall: "Brief Normal",
        formatSmallDesc: "25 x 17cm / bis 100g / < 2cm",
        formatBig: "Brief Gross",
        formatBigDesc: "35 x 25 cm / bis 1000g / < 2cm",
        shippingTitle: "Brief Versenden - Versandart",
        shippingQuestion: "Wie möchten Sie ihre Sendung versenden?",
        bPost: "B-Post",
        aPost: "A-Post",
        express: "Express",
        extrasTitle: "Brief Versenden - Zusatzleistungen",
        extrasQuestion: "Bitte wählen Sie allfällige Zusatzleistungen aus (Mehrfachauswahl möglich):",
        extraRegistered: "Einschreiben",
        extraPrepaid: "Bereits vorfrankiert",
        extraFormat: "Format-Zuschlag"
      },
      payment: {
        scanTitle: "Einzahlen",
        scanInstruction: "Bitte platzieren Sie den QR-Code unter der Dokumentenkamera.",
        scanAction: "QR-Code scannen",
        detailsTitle: "Einzahlen - Zahlungsdetails",
        detailsIntro: "Bitte überprüfen Sie die Zahlungsdetails.",
        fieldIban: "Konto / IBAN",
        fieldAmount: "Betrag CHF",
        fieldRef: "Referenz",
        receiverTitle: "Einzahlen - Zahlungsempfänger",
        confirmTitle: "Einzahlen - Bestätigung",
        confirmQuestion: "Sind alle Angaben korrekt?",
        confirmYes: "Ja\nWeiter zur Abrechnung",
        confirmNo: "Nein\nZurück zur Eingabe",
        summaryTitle: "Bestätigung Einzahlung",
        summaryAccount: "auf Konto"
      },
      chat: {
        introTitle: "Wie kann ich helfen?",
        introDesc: "Tippen Sie auf das Mikrofon und stellen Sie Ihre Frage.",
        listening: "Ich höre zu...",
        sources: "Quellen:",
        tryAgain: "Neue Frage stellen"
      }
    }
};

// Creating translations for other languages
const createTranslation = (lang: string, overrides: any = {}): TranslationData => {
   return mergeTranslations(DE_DEFAULTS, overrides);
};

export const TRANSLATIONS: Record<Language, TranslationData> = {
  de: DE_DEFAULTS,
  fr: createTranslation('fr', {
    topTitle: "PostAssistant",
    pageTitle: "Bienvenue à la Poste",
    chatHeaderTitle: "Chat PostAssistant",
    chatPlaceholder: "Posez votre question…",
    chatSendLabel: "Envoyer",
    tiles: {
      self: {
        title: "Assistant Self-Service",
        desc: "Effectuez vos opérations postales directement ici en libre-service.",
        btnPacket: "Expédier un colis",
        btnLetter: "Envoyer une lettre",
        btnPayment: "Versement (par carte)",
        btnOther: "Tout le reste"
      },
      video: {
        title: "Conseil vidéo",
        desc: "Conseil personnalisé par appel vidéo avec nos experts.",
        btnText: "Démarrer le conseil"
      }
    },
    ui: {
      back: "Retour",
      next: "Suivant",
      confirm: "Confirmer",
      cancel: "Annuler",
      finish: "Terminer",
      pay: "Payer",
      thinking: "Je réfléchis...",
      errorGeneric: "Une erreur est survenue.",
      errorMicrophone: "Erreur microphone.",
    },
    selfService: {
      title: "Affranchir un colis",
      titleLetter: "Envoyer une lettre",
      titlePayment: "Versement",
      titleChat: "Info Poste",
      steps: {
        start: "Démarrer",
        weigh: "Peser",
        address: "Adresse",
        format: "Format",
        options: "Expédition",
        pay: "Paiement",
        done: "Fin",
        scan: "Scan",
        details: "Détails",
        check: "Contrôle"
      },
      franking: {
        destCH: "Suisse / Liechtenstein",
        destInt: "Étranger",
        destIntNote: "Expédition à l'étranger non disponible ici.",
        weighIntro: "Placez votre colis sur la balance.",
        weighAction: "Peser le colis",
        weighing: "Analyse du colis...",
        detectedLabel: "Poids et dimensions détectés",
        weight: "Poids",
        addressSender: "Expéditeur",
        addressReceiver: "Saisir le destinataire",
        isCompany: "Entreprise",
        isPrivate: "Particulier",
        fields: {
          name: "Nom, Prénom",
          street: "Rue, N°",
          zip: "NPA",
          city: "Localité"
        },
        shippingMethod: "Choisir le mode d'expédition",
        economy: "PostPac Economy",
        priority: "PostPac Priority",
        duration2days: "2 jours ouvrables",
        duration1day: "Jour ouvrable suivant",
        extras: "Ajouter des prestations complémentaires",
        signature: "Signature",
        total: "Total",
        payTerminal: "Veuillez utiliser le terminal de paiement.",
        payInstruction: "Paiement espèces/TWINT impossible",
        payButton: "Confirmer le paiement",
        successTitle: "Opération réussie",
        instruction1: "Prendre la quittance.",
        instruction2: "Conserver le justificatif.",
        instruction3: "Opération terminée.",
        feedbackTitle: "Êtes-vous satisfait ?",
        feedbackThanks: "Merci de votre visite !"
      },
      letter: {
        addressCheckTitle: "Envoyer une lettre - Adresse",
        addressCheckQuestion: "L'adresse figure-t-elle déjà sur la lettre ?",
        addressCheckYes: "Oui\nAdresse présente",
        addressCheckNo: "Non\nSaisir l'adresse",
        formatTitle: "Envoyer une lettre - Format",
        formatQuestion: "Quel est le format de votre envoi ?",
        formatSmall: "Lettre standard",
        formatSmallDesc: "25 x 17cm / max 100g / < 2cm",
        formatBig: "Grande lettre",
        formatBigDesc: "35 x 25 cm / max 1000g / < 2cm",
        shippingTitle: "Envoyer une lettre - Mode d'expédition",
        shippingQuestion: "Comment souhaitez-vous expédier votre envoi ?",
        bPost: "Courrier B",
        aPost: "Courrier A",
        express: "Express",
        extrasTitle: "Envoyer une lettre - Prestations",
        extrasQuestion: "Veuillez sélectionner les prestations complémentaires :",
        extraRegistered: "Recommandé",
        extraPrepaid: "Déjà affranchi",
        extraFormat: "Supplément format"
      },
      payment: {
        scanTitle: "Verser",
        scanInstruction: "Placez le code QR sous la caméra.",
        scanAction: "Scanner le code QR",
        detailsTitle: "Détails du paiement",
        detailsIntro: "Veuillez vérifier les détails.",
        fieldIban: "Compte / IBAN",
        fieldAmount: "Montant CHF",
        fieldRef: "Référence",
        receiverTitle: "Bénéficiaire",
        confirmTitle: "Confirmation",
        confirmQuestion: "Les données sont-elles correctes ?",
        confirmYes: "Oui\nContinuer",
        confirmNo: "Non\nCorriger",
        summaryTitle: "Confirmation versement",
        summaryAccount: "sur le compte"
      },
      chat: {
        introTitle: "Comment puis-je vous aider ?",
        introDesc: "Appuyez sur le micro et posez votre question.",
        listening: "J'écoute...",
        sources: "Sources :",
        tryAgain: "Nouvelle question"
      }
    }
  }),
  it: createTranslation('it', {
    topTitle: "PostAssistant",
    pageTitle: "Benvenuti alla Posta",
    chatHeaderTitle: "Chat PostAssistant",
    chatPlaceholder: "Scrivi la tua domanda...",
    chatSendLabel: "Invia",
    tiles: {
       self: {
        title: "Assistente Self-Service",
        desc: "Svolgete le vostre operazioni postali direttamente qui.",
        btnPacket: "Spedire un pacco",
        btnLetter: "Inviare una lettera",
        btnPayment: "Versamento (con carta)",
        btnOther: "Tutto il resto"
       },
       video: {
        title: "Consulenza video",
        desc: "Consulenza personale tramite videochiamata.",
        btnText: "Avviare consulenza"
      }
    },
    ui: {
      back: "Indietro",
      next: "Avanti",
      confirm: "Confermare",
      cancel: "Annullare",
      finish: "Terminare",
      pay: "Pagare",
      thinking: "Sto pensando...",
      errorGeneric: "Si è verificato un errore.",
      errorMicrophone: "Errore microfono.",
    },
    selfService: {
      title: "Affrancare pacco",
      titleLetter: "Inviare lettera",
      titlePayment: "Versamento",
      titleChat: "Info Posta",
      steps: {
        start: "Inizio",
        weigh: "Pesare",
        address: "Indirizzo",
        format: "Formato",
        options: "Spedizione",
        pay: "Pagamento",
        done: "Fine",
        scan: "Scansione",
        details: "Dettagli",
        check: "Verifica"
      },
      franking: {
        destCH: "Svizzera / Liechtenstein",
        destInt: "Estero",
        destIntNote: "Spedizione all'estero non disponibile qui.",
        weighIntro: "Posizionate il pacco sulla bilancia.",
        weighAction: "Pesare pacco",
        weighing: "Analisi del pacco...",
        detectedLabel: "Peso e dimensioni rilevati",
        weight: "Peso",
        addressSender: "Mittente",
        addressReceiver: "Inserire destinatario",
        isCompany: "Ditta",
        isPrivate: "Privato",
        fields: {
          name: "Cognome, Nome",
          street: "Via, N.",
          zip: "NPA",
          city: "Località"
        },
        shippingMethod: "Scegliere modalità di spedizione",
        economy: "PostPac Economy",
        priority: "PostPac Priority",
        duration2days: "2 giorni lavorativi",
        duration1day: "Giorno lavorativo successivo",
        extras: "Aggiungi prestazioni complementari",
        signature: "Signature",
        total: "Totale",
        payTerminal: "Utilizzare il terminale di pagamento.",
        payInstruction: "Pagamento in contanti/TWINT non possibile",
        payButton: "Confermare pagamento",
        successTitle: "Operazione riuscita",
        instruction1: "Ritirare la ricevuta.",
        instruction2: "Conservare la ricevuta.",
        instruction3: "Operazione terminata.",
        feedbackTitle: "Siete soddisfatti?",
        feedbackThanks: "Grazie per la visita!"
      },
      letter: {
        addressCheckTitle: "Inviare lettera - Indirizzo",
        addressCheckQuestion: "L'indirizzo è già presente sulla lettera?",
        addressCheckYes: "Sì\nIndirizzo presente",
        addressCheckNo: "No\nInserire indirizzo",
        formatTitle: "Inviare lettera - Formato",
        formatQuestion: "Qual è il formato dell'invio?",
        formatSmall: "Lettera standard",
        formatSmallDesc: "25 x 17cm / max 100g / < 2cm",
        formatBig: "Lettera grande",
        formatBigDesc: "35 x 25 cm / max 1000g / < 2cm",
        shippingTitle: "Inviare lettera - Spedizione",
        shippingQuestion: "Come desiderate spedire l'invio?",
        bPost: "Posta B",
        aPost: "Posta A",
        express: "Express",
        extrasTitle: "Inviare lettera - Prestazioni",
        extrasQuestion: "Selezionare le prestazioni complementari:",
        extraRegistered: "Raccomandata",
        extraPrepaid: "Già affrancato",
        extraFormat: "Supplemento formato"
      },
      payment: {
        scanTitle: "Versamento",
        scanInstruction: "Posizionare il codice QR sotto la telecamera.",
        scanAction: "Scansionare codice QR",
        detailsTitle: "Dettagli pagamento",
        detailsIntro: "Verificare i dettagli.",
        fieldIban: "Conto / IBAN",
        fieldAmount: "Importo CHF",
        fieldRef: "Riferimento",
        receiverTitle: "Beneficiario",
        confirmTitle: "Conferma",
        confirmQuestion: "I dati sono corretti?",
        confirmYes: "Sì\nAvanti",
        confirmNo: "No\nCorreggere",
        summaryTitle: "Conferma versamento",
        summaryAccount: "sul conto"
      },
      chat: {
        introTitle: "Come posso aiutare?",
        introDesc: "Tocca il microfono e fai la tua domanda.",
        listening: "Ascolto...",
        sources: "Fonti:",
        tryAgain: "Nuova domanda"
      }
    }
  }),
  en: createTranslation('en', {
    topTitle: "PostAssistant",
    pageTitle: "Welcome to Swiss Post",
    chatHeaderTitle: "PostAssistant Chat",
    chatPlaceholder: "Type your question...",
    chatSendLabel: "Send",
    tiles: {
       self: {
        title: "Self-Service Assistant",
        desc: "Handle your postal services directly here using self-service.",
        btnPacket: "Send a parcel",
        btnLetter: "Send a letter",
        btnPayment: "Payment (card)",
        btnOther: "Everything else"
       },
       video: {
        title: "Video Consultation",
        desc: "Personal advice via video call with our experts.",
        btnText: "Start consultation"
      }
    },
    ui: {
      back: "Back",
      next: "Next",
      confirm: "Confirm",
      cancel: "Cancel",
      finish: "Finish",
      pay: "Pay",
      thinking: "Thinking...",
      errorGeneric: "An error occurred.",
      errorMicrophone: "Microphone error.",
    },
    selfService: {
       title: "Frank a parcel",
       titleLetter: "Send a letter",
       titlePayment: "Payment",
       titleChat: "Post Info",
       steps: {
        start: "Start",
        weigh: "Weigh",
        address: "Address",
        format: "Format",
        options: "Shipping",
        pay: "Payment",
        done: "Done",
        scan: "Scan",
        details: "Details",
        check: "Check"
      },
      franking: {
        destCH: "Switzerland / Liechtenstein",
        destInt: "International",
        destIntNote: "International shipping not available here.",
        weighIntro: "Place your parcel on the scale to start.",
        weighAction: "Weigh parcel",
        weighing: "Analyzing parcel...",
        detectedLabel: "Weight and dimensions detected",
        weight: "Weight",
        addressSender: "Sender",
        addressReceiver: "Enter recipient",
        isCompany: "Company",
        isPrivate: "Private",
        fields: {
          name: "Name, First name",
          street: "Street, No.",
          zip: "ZIP",
          city: "City"
        },
        shippingMethod: "Select shipping method",
        economy: "PostPac Economy",
        priority: "PostPac Priority",
        duration2days: "2 working days",
        duration1day: "Next working day",
        extras: "Add extra services",
        signature: "Signature",
        total: "Total",
        payTerminal: "Please use the card terminal for payment.",
        payInstruction: "Cash/TWINT payment not possible",
        payButton: "Confirm payment",
        successTitle: "Operation successful",
        instruction1: "Take receipt.",
        instruction2: "Keep payment proof.",
        instruction3: "Process finished.",
        feedbackTitle: "How satisfied are you?",
        feedbackThanks: "Thanks for visiting!"
      },
      letter: {
        addressCheckTitle: "Send Letter - Address",
        addressCheckQuestion: "Is the address already on the letter?",
        addressCheckYes: "Yes\nAddress present",
        addressCheckNo: "No\nEnter address",
        formatTitle: "Send Letter - Format",
        formatQuestion: "What is the format of your item?",
        formatSmall: "Standard Letter",
        formatSmallDesc: "25 x 17cm / max 100g / < 2cm",
        formatBig: "Large Letter",
        formatBigDesc: "35 x 25 cm / max 1000g / < 2cm",
        shippingTitle: "Send Letter - Shipping",
        shippingQuestion: "How would you like to ship your item?",
        bPost: "B-Mail",
        aPost: "A-Mail",
        express: "Express",
        extrasTitle: "Send Letter - Extras",
        extrasQuestion: "Please select any extra services:",
        extraRegistered: "Registered",
        extraPrepaid: "Already franked",
        extraFormat: "Format surcharge"
      },
      payment: {
        scanTitle: "Deposit",
        scanInstruction: "Please place the QR code under the camera.",
        scanAction: "Scan QR Code",
        detailsTitle: "Payment Details",
        detailsIntro: "Please verify the details.",
        fieldIban: "Account / IBAN",
        fieldAmount: "Amount CHF",
        fieldRef: "Reference",
        receiverTitle: "Beneficiary",
        confirmTitle: "Confirmation",
        confirmQuestion: "Are the details correct?",
        confirmYes: "Yes\nContinue",
        confirmNo: "No\nCorrect",
        summaryTitle: "Deposit Confirmation",
        summaryAccount: "to account"
      },
      chat: {
        introTitle: "How can I help?",
        introDesc: "Tap the microphone and ask your question.",
        listening: "Listening...",
        sources: "Sources:",
        tryAgain: "Ask new question"
      }
    }
  }),
  es: createTranslation('es', {
    topTitle: "PostAssistant",
    pageTitle: "Bienvenido a Correos",
    chatHeaderTitle: "Chat PostAssistant",
    chatPlaceholder: "Escribe tu pregunta...",
    chatSendLabel: "Enviar",
    tiles: {
      orakel: {
        title: "Asistente",
        desc: "Pregunte a nuestro asistente de IA.",
        btnText: "Iniciar asistente",
      },
      self: {
        title: "Asistente Autoservicio",
        desc: "Realice sus gestiones postales directamente aquí.",
        btnText: "Enviar paquete",
        btnPacket: "Enviar paquete",
        btnLetter: "Enviar carta",
        btnPayment: "Pago (con tarjeta)",
        btnOther: "Todo lo demás"
      },
      video: {
        title: "Videoconsulta",
        desc: "Asesoramiento personal por videollamada.",
        btnText: "Iniciar consulta",
      },
    },
    ui: {
      back: "Atrás",
      next: "Siguiente",
      confirm: "Confirmar",
      cancel: "Cancelar",
      finish: "Finalizar",
      pay: "Pagar",
      thinking: "Pensando...",
      welcomeChat: "¡Hola! Soy tu PostAssistant. ¿Cómo puedo ayudarte?",
      errorGeneric: "Ha ocurrido un error.",
      errorMicrophone: "Error de micrófono.",
      retry: "Reintentar"
    },
    selfService: {
      title: "Franquear paquete",
      titleLetter: "Enviar carta",
      titlePayment: "Pago",
      titleChat: "Info Correos",
      steps: {
        start: "Inicio",
        weigh: "Pesar",
        address: "Dirección",
        format: "Formato",
        options: "Envío",
        pay: "Pago",
        done: "Fin",
        scan: "Escanear",
        details: "Detalles",
        check: "Revisión"
      },
      franking: {
        destCH: "Suiza / Liechtenstein",
        destInt: "Extranjero",
        destIntNote: "Envío al extranjero no disponible aquí.",
        weighIntro: "Coloque su paquete en la balanza.",
        weighAction: "Pesar paquete",
        weighing: "Analizando paquete...",
        detectedLabel: "Peso y dimensiones detectados",
        weight: "Peso",
        length: "Largo",
        width: "Ancho",
        height: "Alto",
        addressSender: "Remitente",
        addressReceiver: "Registrar destinatario",
        isCompany: "Empresa",
        isPrivate: "Particular",
        fields: {
          name: "Nombre, Apellido",
          street: "Calle, Nº",
          zip: "CP",
          city: "Ciudad"
        },
        shippingMethod: "Seleccionar envío",
        economy: "PostPac Economy",
        priority: "PostPac Priority",
        duration2days: "2 días laborables",
        duration1day: "Siguiente día laborable",
        extras: "Añadir servicios adicionales",
        signature: "Firma",
        total: "Total",
        payTerminal: "Por favor, use el terminal de pago.",
        payInstruction: "No se admite efectivo/TWINT",
        payButton: "Confirmar pago",
        successTitle: "Operación exitosa",
        instruction1: "Tome el recibo.",
        instruction2: "Guarde el comprobante.",
        instruction3: "Proceso finalizado.",
        feedbackTitle: "¿Está satisfecho?",
        feedbackThanks: "¡Gracias por su visita!"
      },
      letter: {
        addressCheckTitle: "Enviar carta - Dirección",
        addressCheckQuestion: "¿La dirección ya está en la carta?",
        addressCheckYes: "Sí\nDirección presente",
        addressCheckNo: "No\nIntroducir dirección",
        formatTitle: "Enviar carta - Formato",
        formatQuestion: "¿Cuál es el formato de su envío?",
        formatSmall: "Carta estándar",
        formatSmallDesc: "25 x 17cm / máx 100g / < 2cm",
        formatBig: "Carta grande",
        formatBigDesc: "35 x 25 cm / máx 1000g / < 2cm",
        shippingTitle: "Enviar carta - Envío",
        shippingQuestion: "¿Cómo desea enviar su correspondencia?",
        bPost: "Correo B",
        aPost: "Correo A",
        express: "Express",
        extrasTitle: "Enviar carta - Extras",
        extrasQuestion: "Seleccione servicios adicionales:",
        extraRegistered: "Certificado",
        extraPrepaid: "Ya franqueado",
        extraFormat: "Suplemento formato"
      },
      payment: {
        scanTitle: "Ingresar",
        scanInstruction: "Coloque el código QR bajo la cámara.",
        scanAction: "Escanear código QR",
        detailsTitle: "Detalles del pago",
        detailsIntro: "Verifique los detalles.",
        fieldIban: "Cuenta / IBAN",
        fieldAmount: "Importe CHF",
        fieldRef: "Referencia",
        receiverTitle: "Beneficiario",
        confirmTitle: "Confirmación",
        confirmQuestion: "¿Son correctos los datos?",
        confirmYes: "Sí\nContinuar",
        confirmNo: "No\nCorregir",
        summaryTitle: "Confirmación ingreso",
        summaryAccount: "en cuenta"
      },
      chat: {
        introTitle: "¿Cómo puedo ayudar?",
        introDesc: "Toque el micrófono y haga su pregunta.",
        listening: "Escuchando...",
        sources: "Fuentes:",
        tryAgain: "Nueva pregunta"
      }
    }
  }),
  pt: createTranslation('pt', {
    topTitle: "PostAssistant",
    pageTitle: "Bem-vindo aos Correios",
    chatHeaderTitle: "Chat PostAssistant",
    chatPlaceholder: "Escreva a sua pergunta...",
    chatSendLabel: "Enviar",
    tiles: {
      orakel: {
        title: "Assistente",
        desc: "Pergunte ao nosso assistente de IA.",
        btnText: "Iniciar assistente",
      },
      self: {
        title: "Assistente Self-Service",
        desc: "Realize os seus serviços postais diretamente aqui.",
        btnText: "Enviar encomenda",
        btnPacket: "Enviar encomenda",
        btnLetter: "Enviar carta",
        btnPayment: "Pagamento (cartão)",
        btnOther: "Tudo o resto"
      },
      video: {
        title: "Videoconsulta",
        desc: "Aconselhamento pessoal por videochamada.",
        btnText: "Iniciar consulta",
      },
    },
    ui: {
      back: "Voltar",
      next: "Seguinte",
      confirm: "Confirmar",
      cancel: "Cancelar",
      finish: "Terminar",
      pay: "Pagar",
      thinking: "A pensar...",
      welcomeChat: "Olá! Sou o seu PostAssistant. Como posso ajudar?",
      errorGeneric: "Ocorreu um erro.",
      errorMicrophone: "Erro no microfone.",
      retry: "Tentar novamente"
    },
    selfService: {
      title: "Franquear encomenda",
      titleLetter: "Enviar carta",
      titlePayment: "Pagamento",
      titleChat: "Info Correios",
      steps: {
        start: "Início",
        weigh: "Pesar",
        address: "Endereço",
        format: "Formato",
        options: "Envio",
        pay: "Pagamento",
        done: "Fim",
        scan: "Digitalizar",
        details: "Detalhes",
        check: "Verificação"
      },
      franking: {
        destCH: "Suíça / Liechtenstein",
        destInt: "Estrangeiro",
        destIntNote: "Envio para o estrangeiro não disponível aqui.",
        weighIntro: "Coloque a sua encomenda na balança.",
        weighAction: "Pesar encomenda",
        weighing: "A analisar encomenda...",
        detectedLabel: "Peso e dimensões detetados",
        weight: "Peso",
        length: "Comprimento",
        width: "Largura",
        height: "Altura",
        addressSender: "Remetente",
        addressReceiver: "Registar destinatário",
        isCompany: "Empresa",
        isPrivate: "Particular",
        fields: {
          name: "Nome, Apelido",
          street: "Rua, Nº",
          zip: "CP",
          city: "Localidade"
        },
        shippingMethod: "Selecionar envio",
        economy: "PostPac Economy",
        priority: "PostPac Priority",
        duration2days: "2 dias úteis",
        duration1day: "Dia útil seguinte",
        extras: "Adicionar serviços extra",
        signature: "Assinatura",
        total: "Total",
        payTerminal: "Por favor, use o terminal de pagamento.",
        payInstruction: "Não é possível pagar em dinheiro/TWINT",
        payButton: "Confirmar pagamento",
        successTitle: "Operação com sucesso",
        instruction1: "Retirar o recibo.",
        instruction2: "Guardar o comprovativo.",
        instruction3: "Processo terminado.",
        feedbackTitle: "Está satisfeito?",
        feedbackThanks: "Obrigado pela visita!"
      },
      letter: {
        addressCheckTitle: "Enviar carta - Endereço",
        addressCheckQuestion: "O endereço já está na carta?",
        addressCheckYes: "Sim\nEndereço presente",
        addressCheckNo: "Não\nInserir endereço",
        formatTitle: "Enviar carta - Formato",
        formatQuestion: "Qual é o formato do seu envio?",
        formatSmall: "Carta padrão",
        formatSmallDesc: "25 x 17cm / máx 100g / < 2cm",
        formatBig: "Carta grande",
        formatBigDesc: "35 x 25 cm / máx 1000g / < 2cm",
        shippingTitle: "Enviar carta - Envio",
        shippingQuestion: "Como deseja enviar o seu correio?",
        bPost: "Correio B",
        aPost: "Correio A",
        express: "Expresso",
        extrasTitle: "Enviar carta - Extras",
        extrasQuestion: "Selecione serviços adicionais:",
        extraRegistered: "Registado",
        extraPrepaid: "Já franqueado",
        extraFormat: "Suplemento formato"
      },
      payment: {
        scanTitle: "Depositar",
        scanInstruction: "Coloque o código QR sob a câmara.",
        scanAction: "Ler código QR",
        detailsTitle: "Detalhes do pagamento",
        detailsIntro: "Verifique os detalhes.",
        fieldIban: "Conta / IBAN",
        fieldAmount: "Montante CHF",
        fieldRef: "Referência",
        receiverTitle: "Beneficiário",
        confirmTitle: "Confirmação",
        confirmQuestion: "Os dados estão corretos?",
        confirmYes: "Sim\nContinuar",
        confirmNo: "Não\nCorrigir",
        summaryTitle: "Confirmação depósito",
        summaryAccount: "na conta"
      },
      chat: {
        introTitle: "Como posso ajudar?",
        introDesc: "Toque no microfone e faça a sua pergunta.",
        listening: "A ouvir...",
        sources: "Fontes:",
        tryAgain: "Nova pergunta"
      }
    }
  })
};

export const LANGUAGES: { code: Language; label: string }[] = [
  { code: 'de', label: 'Deutsch' },
  { code: 'fr', label: 'Français' },
  { code: 'it', label: 'Italiano' },
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Español' },
  { code: 'pt', label: 'Português' },
];
