
-- Tabelle für globale Einstellungen
CREATE TABLE IF NOT EXISTS public.app_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    voice_name text DEFAULT 'Puck',
    politeness text DEFAULT 'formal', -- 'formal' oder 'casual'
    global_prompt text DEFAULT ''
);

-- Initiale Zeile einfügen, falls leer
INSERT INTO public.app_settings (id, voice_name, politeness)
SELECT 1, 'Puck', 'formal'
WHERE NOT EXISTS (SELECT 1 FROM public.app_settings);

-- Tabelle für Prozesse
CREATE TABLE IF NOT EXISTS public.processes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_key text NOT NULL UNIQUE, -- 'packet', 'letter', 'payment', 'tracking'
    label text NOT NULL,
    is_enabled boolean DEFAULT true,
    custom_prompt text DEFAULT '',
    response_length text DEFAULT 'medium', -- 'short', 'medium', 'long'
    support_intensity text DEFAULT 'proactive' -- 'passive', 'proactive'
);

-- Initiale Prozesse einfügen (Upsert)
INSERT INTO public.processes (process_key, label, is_enabled, support_intensity)
VALUES 
('packet', 'Paket aufgeben', true, 'proactive'),
('letter', 'Brief versenden', true, 'passive'),
('payment', 'Einzahlung', true, 'proactive'),
('tracking', 'Sendungsverfolgung', true, 'passive')
ON CONFLICT (process_key) DO NOTHING;

-- Tabelle für Dokumente (Knowledge Base)
CREATE TABLE IF NOT EXISTS public.knowledge_documents (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    title text NOT NULL,
    content text NOT NULL,
    scope text NOT NULL, -- 'global' oder 'process'
    process_key text, -- Foreign Key zu processes.process_key (optional, wenn scope='process')
    is_active boolean DEFAULT true,
    created_at timestamptz DEFAULT now()
);

-- Row Level Security (RLS) aktivieren
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.processes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.knowledge_documents ENABLE ROW LEVEL SECURITY;

-- Einfache Policies für Anon-Zugriff (falls via Client zugegriffen wird)
-- WARNUNG: Dies erlaubt jedem User alles zu sehen/ändern. Für Produktion anpassen!
CREATE POLICY "Enable read access for all users" ON public.app_settings FOR SELECT USING (true);
CREATE POLICY "Enable update access for all users" ON public.app_settings FOR UPDATE USING (true);

CREATE POLICY "Enable read access for all users" ON public.processes FOR SELECT USING (true);
CREATE POLICY "Enable update access for all users" ON public.processes FOR UPDATE USING (true);

CREATE POLICY "Enable read access for all users" ON public.knowledge_documents FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.knowledge_documents FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable delete access for all users" ON public.knowledge_documents FOR DELETE USING (true);
